services:
  # --- APLICACIÓN PRINCIPAL ---
  app:
    image: ghcr.io/felondz/controlapp:latest
    container_name: controlapp_app
    restart: unless-stopped

    # Leemos todo del .env (Ahora controlará Redis y Meilisearch)
    env_file: ./.env

    # La app espera a que estos servicios inicien primero
    depends_on:
      - db
      - redis
      - meilisearch

    volumes:
      - ./storage:/var/www/html/storage

    networks:
      - proxy # Para Traefik (Público)
      - internal # Para DB, Redis y Meilisearch (Privado)

    labels:
      - "traefik.enable=true"

      # --- Router Principal (controlapp.site) ---
      - "traefik.http.routers.controlapp-root-http.rule=Host(`controlapp.site`)"
      - "traefik.http.routers.controlapp-root-http.entrypoints=web"
      - "traefik.http.routers.controlapp-root-http.middlewares=cattleya-https-redirect"
      - "traefik.http.routers.controlapp-root-https.rule=Host(`controlapp.site`)"
      - "traefik.http.routers.controlapp-root-https.entrypoints=websecure"
      - "traefik.http.routers.controlapp-root-https.tls.certresolver=letsencrypt"

      # --- Router API (api.controlapp.site) ---
      - "traefik.http.routers.controlapp-api-http.rule=Host(`api.controlapp.site`)"
      - "traefik.http.routers.controlapp-api-http.entrypoints=web"
      - "traefik.http.routers.controlapp-api-http.middlewares=cattleya-https-redirect"
      - "traefik.http.routers.controlapp-api-https.rule=Host(`api.controlapp.site`)"
      - "traefik.http.routers.controlapp-api-https.entrypoints=websecure"
      - "traefik.http.routers.controlapp-api-https.tls.certresolver=letsencrypt"

      # --- Servicio ---
      - "traefik.http.services.controlapp-service.loadbalancer.server.port=80"

  # --- BASE DE DATOS ---
  db:
    image: mysql:8.0
    container_name: controlapp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  # --- REDIS (Cache & Colas) ---
  redis:
    image: redis:alpine
    container_name: controlapp_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - internal

  # --- MEILISEARCH (Búsqueda Avanzada) ---
  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: controlapp_meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    volumes:
      - meili_data:/meili_data
    networks:
      - internal

# --- REDES ---
networks:
  proxy:
    external: true # Red de Traefik
  internal:
    driver: bridge # Red interna de la app

# --- VOLÚMENES ---
volumes:
  db_data:
  redis_data:
  meili_data:
