<?php

namespace App\Modules\Inventory\Listeners;

use App\Modules\Finance\Events\SupplyContractExecuted;
use App\Modules\Inventory\Models\InventoryTransaction;
use App\Modules\Inventory\Models\InventoryItem;
use Illuminate\Support\Facades\Log;

class CreateInventoryDraftEntry
{
    /**
     * Handle the event.
     *
     * @param  SupplyContractExecuted  $event
     * @return void
     */
    public function handle(SupplyContractExecuted $event)
    {
        $contract = $event->contract;
        $invoice = $event->invoice;

        Log::info("Generating Inventory Draft for Contract [{$contract->name}]");

        if (empty($contract->items)) {
            Log::warning("Contract [{$contract->id}] has no items defined.");
            return;
        }

        // Parse items from contract JSON
        // Expected format: [{"sku": "CODE", "qty": 10, "price": 100}] or similar
        foreach ($contract->items as $itemData) {
            $sku = $itemData['sku'] ?? null;
            $qty = $itemData['qty'] ?? 0;
            $unitPrice = $itemData['price'] ?? 0;

            if (!$sku)
                continue;

            // Find Inventory Item by SKU in the same project
            $inventoryItem = InventoryItem::where('proyecto_id', $contract->proyecto_id)
                ->where('sku', $sku)
                ->first();

            if ($inventoryItem) {
                InventoryTransaction::create([
                    'proyecto_id' => $contract->proyecto_id,
                    'inventory_item_id' => $inventoryItem->id,
                    'user_id' => null, // Automated system action
                    'type' => 'purchase',
                    'quantity' => $qty, // Positive for purchase
                    'unit_price' => $unitPrice,
                    'total_amount' => $qty * $unitPrice,

                    // Link to the SupplyContract (or Invoice) linked polymorphically
                    'reference_type' => get_class($contract),
                    'reference_id' => $contract->id,

                    'status' => 'draft', // User must confirm reception physicaly
                    'notes' => "Autogenerated from Supply Contract: {$contract->name}. Linked Invoice: #{$invoice->id}",
                    'transaction_date' => now(),
                ]);

                Log::info("Draft entry created for ITEM {$sku}");
            } else {
                Log::warning("SKU {$sku} not found in Inventory for Project {$contract->proyecto_id}. Skipping.");
            }
        }
    }
}
