<?php

namespace App\Modules\Inventory\Listeners;

use App\Core\Events\Contracts\ModuleEvent;
use App\Modules\Finance\Events\SupplyContractExecuted;
use App\Modules\Finance\Models\SupplyContract;
use App\Modules\Inventory\Models\InventoryTransaction;
use App\Modules\Inventory\Models\InventoryItem;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Log;

/**
 * CreateInventoryDraftEntry Listener
 * 
 * Creates draft inventory entries when a supply contract is executed.
 * Runs asynchronously via Redis queue.
 */
class CreateInventoryDraftEntry implements ShouldQueue
{
    use InteractsWithQueue;

    /**
     * The name of the connection the job should be sent to.
     *
     * @var string|null
     */
    public $connection = 'redis';

    /**
     * Handle the event.
     *
     * @param ModuleEvent $event
     * @return void
     */
    public function handle(ModuleEvent $event): void
    {
        // Only handle finance.contract.executed
        if ($event->getName() !== 'finance.contract.executed') {
            return;
        }

        // Get data from event
        if ($event instanceof SupplyContractExecuted) {
            $contract = $event->contract;
            $invoice = $event->invoice;
        } else {
            // Fallback: load from payload
            $contractId = $event->get('contract_id');
            $invoiceId = $event->get('invoice_id');
            
            /** @var SupplyContract|null $contract */
            $contract = SupplyContract::find($contractId);
            
            if (!$contract) {
                Log::channel('modules')->warning("CreateInventoryDraftEntry: Could not find contract", [
                    'contract_id' => $contractId,
                ]);
                return;
            }
            $invoice = (object) ['id' => $invoiceId];
        }

        Log::channel('modules')->info("CreateInventoryDraftEntry: Generating Inventory Draft for Contract [{$contract->name}]");

        if (empty($contract->items)) {
            Log::channel('modules')->warning("CreateInventoryDraftEntry: Contract [{$contract->id}] has no items defined.");
            return;
        }

        // Parse items from contract JSON
        // Expected format: [{"sku": "CODE", "qty": 10, "price": 100}] or similar
        foreach ($contract->items as $itemData) {
            $sku = $itemData['sku'] ?? null;
            $qty = $itemData['qty'] ?? 0;
            $unitPrice = $itemData['price'] ?? 0;

            if (!$sku)
                continue;

            // Find Inventory Item by SKU in the same project
            $inventoryItem = InventoryItem::where('proyecto_id', $contract->proyecto_id)
                ->where('sku', $sku)
                ->first();

            if ($inventoryItem) {
                InventoryTransaction::create([
                    'proyecto_id' => $contract->proyecto_id,
                    'inventory_item_id' => $inventoryItem->id,
                    'user_id' => null, // Automated system action
                    'type' => 'purchase',
                    'quantity' => $qty, // Positive for purchase
                    'unit_price' => $unitPrice,
                    'total_amount' => $qty * $unitPrice,

                    // Link to the SupplyContract (or Invoice) linked polymorphically
                    'reference_type' => get_class($contract),
                    'reference_id' => $contract->id,

                    'status' => 'draft', // User must confirm reception physically
                    'notes' => "Autogenerated from Supply Contract: {$contract->name}. Linked Invoice: #{$invoice->id}",
                    'transaction_date' => now(),
                ]);

                Log::channel('modules')->info("CreateInventoryDraftEntry: Draft entry created for ITEM {$sku}");
            } else {
                Log::channel('modules')->warning("CreateInventoryDraftEntry: SKU {$sku} not found in Inventory for Project {$contract->proyecto_id}. Skipping.");
            }
        }
    }
}
