#!/bin/bash

# Traducciones básicas - términos comunes
sed -i 's/Guía completa sobre/Complete guide about/g' "$1"
sed -i 's/Tabla de Contenidos/Table of Contents/g' "$1"
sed -i 's/Visión General/Overview/g' "$1"
sed -i 's/Flujo de Autenticación/Authentication Flow/g' "$1"
sed -i 's/Registro de Usuarios/User Registration/g' "$1"
sed -i 's/Login y Tokens/Login and Tokens/g' "$1"
sed -i 's/Verificación de Email/Email Verification/g' "$1"
sed -i 's/Autorización/Authorization/g' "$1"
sed -i 's/Seguridad/Security/g' "$1"
sed -i 's/Solución de problemas/Troubleshooting/g' "$1"
sed -i 's/Paso 1:/Step 1:/g' "$1"
sed -i 's/Paso 2:/Step 2:/g' "$1"
sed -i 's/Paso 3:/Step 3:/g' "$1"
sed -i 's/Paso 4:/Step 4:/g' "$1"
sed -i 's/Paso 5:/Step 5:/g' "$1"
sed -i 's/Requerido/Required/g' "$1"
sed -i 's/Máximo/Maximum/g' "$1"
sed -i 's/Mínimo/Minimum/g' "$1"
sed -i 's/caracteres/characters/g' "$1"
sed -i 's/email válido/valid email/g' "$1"
sed -i 's/Usuario registrado/User registered/g' "$1"
sed -i 's/Endpoint/Endpoint/g' "$1"

